# Generated by Django 4.0.6 on 2022-07-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HesabMoaseseh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=10)),
                ('cart_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Khayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('national_code', models.CharField(max_length=10, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('address', models.TextField(null=True)),
                ('post_code', models.CharField(max_length=10, null=True)),
                ('creating_date', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Madadjo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('national_code', models.CharField(max_length=10, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('address', models.TextField(null=True)),
                ('post_code', models.CharField(max_length=10, null=True)),
                ('creating_date', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TahvilgirandehSandogh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('national_code', models.CharField(max_length=10, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('create_date', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SandoghKhayerieh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khayer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.khayer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('card_number', models.CharField(max_length=16)),
                ('description', models.TextField(null=True)),
                ('hesab_moaseseh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.hesabmoaseseh')),
                ('khayer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.khayer')),
                ('sandogh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.sandoghkhayerieh')),
                ('tahvilgirandeh_sandogh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.tahvilgirandehsandogh')),
            ],
        ),
        migrations.CreateModel(
            name='Helping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('hesab_moaseseh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.hesabmoaseseh')),
                ('madadjo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.madadjo')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TimeField(auto_now_add=True)),
                ('sandogh_khayerieh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.sandoghkhayerieh')),
                ('tavilgirandeh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.tahvilgirandehsandogh')),
            ],
        ),
    ]
