# Generated by Django 4.0.6 on 2022-07-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_payment_khayer_alter_payment_sandogh_khayerieh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='khayer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.khayer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sandogh_khayerieh',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.sandoghkhayerieh'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tahvilgirandeh_sandogh',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.tahvilgirandehsandogh'),
        ),
    ]
