# Generated by Django 4.0.6 on 2022-07-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_payment_khayer_alter_payment_sandogh_khayerieh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='madadjo',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive'), ('NU', 'Unknown')], default='NU', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
