# Generated by Django 4.0.6 on 2022-07-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_madadjo_status_alter_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='typee',
            field=models.CharField(choices=[('CART', 'Cart'), ('CASH', 'Cash'), ('SANDOGH', 'Sandogh')], default='CASH', max_length=7),
        ),
        migrations.AlterField(
            model_name='madadjo',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('NUKKNOW', 'Unknown')], default='NUKKNOW', max_length=8),
        ),
    ]
