# Generated by Django 4.0.6 on 2022-07-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_payment_typee_alter_madadjo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='typee',
            field=models.CharField(choices=[('CART', 'Cart'), ('CASH', 'Cash'), ('SANDOGH', 'Sandogh')], default='CASH', max_length=7, null=True),
        ),
    ]
