# Generated by Django 4.0.6 on 2022-07-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_payment_typee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khayer',
            name='creating_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
