# Generated by Django 4.0.6 on 2022-07-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_khayer_creating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khayer',
            name='creating_date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
