# Generated by Django 4.0.6 on 2022-07-23 11:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_khayer_creating_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='has_paid',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='khayer_bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ref_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='sandoghkhayerieh',
            name='code',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sandoghkhayerieh',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('NUKKNOW', 'Unknown')], default='NUKKNOW', max_length=8),
        ),
        migrations.AddField(
            model_name='sandoghkhayerieh',
            name='strting_date',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sandoghkhayerieh',
            name='typee',
            field=models.CharField(choices=[('PLASTICB', 'PlasticBig'), ('PLASTICS', 'PlasticBig'), ('FELEZIB', 'FeleziBig'), ('FELEZIS', 'FeleziSmall')], default=None, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sandoghkhayerieh',
            name='khayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.khayer'),
        ),
    ]
