# Generated by Django 4.0.6 on 2022-07-24 16:15

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_payment_has_paid_payment_khayer_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khayer',
            name='creating_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
