# Generated by Django 4.0.6 on 2022-07-24 16:29

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_khayer_creating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='helping',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='madadjo',
            name='creating_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sandoghkhayerieh',
            name='strting_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tahvilgirandehsandogh',
            name='create_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
