# Generated by Django 4.0.6 on 2022-07-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_payment_authority_alter_khayer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khayer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('NUKKNOW', 'Unknown')], default='NUKKNOW', max_length=8),
        ),
    ]
