# Generated by Django 4.0.6 on 2022-07-27 09:22

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_madadjo_creating_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign',
            old_name='tavilgirandeh',
            new_name='tahvilgirandeh',
        ),
        migrations.AlterField(
            model_name='assign',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
